name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra-ci-cd.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'infra/**'
      - '.github/workflows/infra-ci-cd.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./infra/tf-app
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infra/tf-app
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./infra/tf-app
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        working-directory: ./infra/tf-app
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false